### ISSUE TITLE
Providing filters to Connection.get_report results in JSON_PARSER_ERROR

### ISSUE THREAD

**Issue by JonNorman** [cghall/salesforce-reporting#3]
### Issue
When providing a list of filters to `Connection.get_report`, the response from SalesForce is:
```
[{u'errorCode': u'JSON_PARSER_ERROR', u'message': u'The request body is either invalid or incomplete.'}]
```

Note: this has nothing to do with the filters that are supplied, see below. 

### Reproduce
Make a call to `Connection.get_report`, with a list of filters, for example:

```
filter = {
                'column': 'AMS_Order__c.Name',
                'operator': 'equals',
                'value': 'ORD-1'
                }

filters = [filter]

connection = Connection(username, password, security_token)
connection.get_report('my-report-id', filters)
```

In order to verify that this has nothing to do with the filters, I commented out the [lines in which the filters are appended to the metadata](https://github.com/cghall/salesforce-reporting/blob/master/salesforce_reporting/login.py#L116) and the error persists.

### Cause
I believe that this is due to the [retrieval of the report metadata](https://github.com/cghall/salesforce-reporting/blob/master/salesforce_reporting/login.py#L112), to which the supplied filters are appended.

Currently this is done by appending `/describe` to the report URL, however at this point the URL already has the  `?includeDetails={}`, which appears to result in a different (or invalid?) metadata object to be passed back. When this metadata is appended to and included in the POST request, we get the above error.

Altering the URL that is passed to `_get_metadata` so that it stops before the `includeDetails` parameter seems to fix this.

**Comment by JonNorman** [comment]
The format of report filters can be seen [here](https://developer.salesforce.com/docs/atlas.en-us.api_analytics.meta/api_analytics/sforce_analytics_rest_api_filter_reportdata.htm); perhaps this has changed recently.

**Comment by anapaularg** [comment]
Finally got this! This package is really useful but this change (https://github.com/cghall/force-retrieve/pull/4!) is not in pypi, I had to fixed this bug myself. Please can you include this change in pypi? I think everybody would appreciate it. Thank you.
